### PR TITLE
Use American spelling for "specialty"

### PR DESCRIPTION
**Pull request by eniraa**
A common complaint amongst those who have completed the qualifier has been the esoteric spelling of the word "specialty". This choice of spelling has truly been disruptive, and this PR seeks to help minimize this disruption.

### CODE REVIEW

**Comment by HRLO77** [comment]
I agree, although this isn't exactly an issue. It was certainly difficult for me for around 10 minutes. But considering we have much more time to complete the qualifier than 10 minutes, it isn't much of a problem

**Comment by eniraa** [comment]
Nonetheless, for many of the applicants, the esoteric spelling of the word constituted the bulk of the difficulty of the qualifier; I believe that the difficulty of a qualifier, especially for beginner-friendly events such as CJ9, should not heavily depend on curveballs such as these.

**Review by Bluenix2 — CHANGES_REQUESTED** [review]
This is more- or less a breaking change at this point, as we cannot change this without breaking both existing qualifiers and in-progress qualifiers.

Therefore, the only viable solution would be to make duplicates in the dictionary. This would most likely complicate the tests a bit and I am not sure how much it'd help.

Besides, if we change this to the American spelling how many will be confused when using the British spelling? That's a hard thing to measure.

I am not sure whether this is a change we will want to make. It'd be happy with a warning to use the correct spelling though - that change is harm-free.

**Comment by eniraa** [comment]
The comment about the spelling being "esoteric" was in jest, but it is less common than the American spelling, especially since both spellings are interchangeable in British English to the best of my knowledge.

**Comment by ionite34** [comment]
> This is more- or less a breaking change at this point, as we cannot change this without breaking both existing qualifiers and in-progress qualifiers.
> 
> Therefore, the only viable solution would be to make duplicates in the dictionary. This would most likely complicate the tests a bit and I am not sure how much it'd help.
> 
> Besides, if we change this to the American spelling how many will be confused when using the British spelling? That's a hard thing to measure.
> 
> I am not sure whether this is a change we will want to make. It'd be happy with a warning to use the correct spelling though - that change is harm-free.

I agree with the warning method to avoid compatibility issues, I have created #5 where a special verbose warning is raised on attempted access of the key `specialty`

**Comment by Bluenix2** [comment]
This was superseded by #5 - nevertheless, thank you for opening this PR!

**Pull request closed without merging**
